import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const read = p => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store = read('content/store.json');
const menus = read('content/menus.json');
const notices = read('content/notices.json');
const events = read('content/events.json');
const out = path.join(root, 'dist');
fs.rmSync(out, {recursive:true, force:true});
fs.mkdirSync(out, {recursive:true});
if (fs.existsSync(path.join(root, 'assets'))) fs.cpSync(path.join(root, 'assets'), path.join(out, 'assets'), {recursive:true});

const notice = (notices.active || []).filter(n => n.enabled).sort((a,b)=>(b.priority||0)-(a.priority||0))[0]?.text || `${store.storeName} · ${store.phone}`;
const menuHtml = (menus.brands || []).map(b => `<section class="card"><h3>${esc(b.emoji)} ${esc(b.name)}</h3>${b.items.map(i => `<div class="row"><span>${esc(i.name)}</span><b>${esc(i.priceDisplay)}</b></div>`).join('')}</section>`).join('');
const eventHtml = (events.events || []).filter(e => e.enabled !== false).map(e => `<article class="event"><b>${esc(e.title || '이벤트')}</b><span>${esc(e.text || '')}</span></article>`).join('');
const mapUrl = `https://map.naver.com/p/search/${encodeURIComponent(store.naverMapSearch)}`;
const schema = {'@context':'https://schema.org','@type':'Restaurant',name:store.storeName,telephone:store.phone,address:{'@type':'PostalAddress',streetAddress:store.address,addressCountry:'KR'},servesCuisine:['치킨','피자','요거트'],url:'https://jadam-maru.pages.dev/'};

const html = `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(store.brandName)} | 무안목포대점</title><meta name="description" content="목포대 앞 치킨·피자·요거트를 한 번에. ${esc(store.storeName)} 전화 주문 ${esc(store.phone)}"><link rel="canonical" href="https://jadam-maru.pages.dev/"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>
:root{--bg:#fffaf4;--ink:#1e1916;--muted:#73675f;--line:#eadfd6;--accent:#8b2f22;--dark:#261d18}*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif;background:var(--bg);color:var(--ink)}a{text-decoration:none;color:inherit}.wrap{max-width:1080px;margin:auto;padding:0 20px}.notice{background:var(--dark);color:#fff;text-align:center;padding:10px;font-size:14px}.nav{height:70px;display:flex;align-items:center;justify-content:space-between}.logo{font-size:24px;font-weight:900}.nav nav{display:flex;gap:18px;color:var(--muted);font-size:14px}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:32px;align-items:center;padding:42px 0 52px}.hero h1{font-size:clamp(42px,6vw,70px);line-height:1.03;letter-spacing:-.05em;margin:0 0 18px}.hero p{font-size:18px;line-height:1.7;color:var(--muted)}.hero img{width:100%;aspect-ratio:1.1/1;object-fit:cover;border-radius:24px;box-shadow:0 20px 60px #0002}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.btn{display:inline-flex;padding:14px 18px;border:1px solid var(--line);background:#fff;border-radius:14px;font-weight:800}.primary{background:var(--accent);border-color:var(--accent);color:#fff}.facts,.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.fact,.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:20px}.fact small{display:block;color:var(--muted);margin-bottom:7px}.title{font-size:30px;margin:42px 0 16px}.card h3{margin:0 0 14px;font-size:22px}.row{display:flex;justify-content:space-between;gap:20px;padding:12px 0;border-top:1px solid #f1e8e0}.row b{white-space:nowrap}.note{color:var(--muted);font-size:13px;line-height:1.6}.event{background:#fff2d9;border:1px solid #efd6a6;border-radius:14px;padding:16px;display:flex;flex-direction:column;gap:7px}.order{margin:46px 0;background:var(--dark);color:#fff;border-radius:24px;padding:28px;display:flex;align-items:center;justify-content:space-between;gap:20px}.order h2{margin:0 0 6px}.order p{margin:0;color:#d7cbc4}.order .btn{color:var(--ink)}footer{border-top:1px solid var(--line);padding:24px 20px 90px;color:var(--muted);font-size:13px;display:flex;justify-content:space-between;gap:16px}.mobile{display:none;position:fixed;left:10px;right:10px;bottom:10px;background:#fff;border:1px solid var(--line);border-radius:16px;padding:8px;box-shadow:0 12px 30px #0002;z-index:5}.mobile a{flex:1;text-align:center;padding:12px;font-weight:800}.mobile .call{background:var(--accent);color:#fff;border-radius:12px}@media(max-width:760px){.nav nav{display:none}.hero{grid-template-columns:1fr;padding-top:20px}.hero img{order:-1;max-height:300px}.facts,.cards{grid-template-columns:1fr}.order{align-items:flex-start;flex-direction:column}footer{flex-direction:column}.mobile{display:flex}.hero h1{font-size:43px}}
</style></head><body><div class="notice">${esc(notice)}</div><header class="wrap nav"><a class="logo" href="#top">${esc(store.brandName)}</a><nav><a href="#menu">메뉴</a><a href="#store">매장정보</a><a href="terms.html">이용약관</a><a href="privacy.html">개인정보</a></nav></header><main id="top"><section class="wrap hero"><div><h1>치킨도, 피자도,<br>요거트도 한 번에.</h1><p>목포대 앞 ${esc(store.storeName)}입니다. 메뉴 고르는 시간은 즐겁게, 주문은 빠르게.</p><div class="actions"><a class="btn primary" href="${esc(store.phoneHref)}">☎ ${esc(store.phone)} 전화 주문</a><a class="btn" href="${mapUrl}" target="_blank" rel="noopener">📍 위치 찾기</a></div></div><img src="assets/hero-food.png" alt="치킨과 피자 대표 이미지"></section><section class="wrap" id="store"><div class="facts"><div class="fact"><small>주소</small><b>${esc(store.address)}</b></div><div class="fact"><small>영업시간</small><b>${esc(store.hours.display)}</b><div class="note">${esc(store.hours.note)}</div></div><div class="fact"><small>주문</small><b>${esc(store.services.join(' · '))}</b></div></div></section><section class="wrap" id="menu"><h2 class="title">한 자리에서 고르는 세 가지 맛</h2><div class="cards">${menuHtml}</div><p class="note">${esc(menus.disclaimer)} · 확인일 ${esc(menus.lastVerified)}</p></section>${eventHtml ? `<section class="wrap"><h2 class="title">지금 안내</h2>${eventHtml}</section>` : ''}<section class="wrap"><div class="order"><div><h2>바로 주문할까요?</h2><p>${esc(store.phone)} · ${esc(store.hours.display)}</p></div><a class="btn" href="${esc(store.phoneHref)}">전화 주문하기</a></div></section></main><footer class="wrap"><div>© ${new Date().getFullYear()} ${esc(store.storeName)}</div><div><a href="terms.html">이용약관</a> · <a href="privacy.html">개인정보처리방침</a></div></footer><div class="mobile"><a href="${mapUrl}" target="_blank" rel="noopener">위치</a><a class="call" href="${esc(store.phoneHref)}">전화 주문</a></div></body></html>`;

const simple = (title, body) => `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | ${esc(store.brandName)}</title><style>body{font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif;max-width:760px;margin:50px auto;padding:0 20px;line-height:1.8;color:#222}a{color:#7b2b20}</style><body><a href="index.html">← ${esc(store.brandName)}</a><h1>${title}</h1>${body}</body></html>`;
const terms = simple('이용약관', `<p>본 사이트는 ${esc(store.storeName)}의 매장 안내와 주문 연결을 위한 정보 페이지입니다.</p><p>메뉴·가격·영업시간은 매장 운영 상황에 따라 변경될 수 있으며 실제 주문 시 확인되는 내용이 우선합니다.</p><p>외부 지도·주문 플랫폼 이용 시 해당 서비스의 이용약관이 적용됩니다.</p><p>시행일: 2026-08-10</p>`);
const privacy = simple('개인정보처리방침', `<p>현재 이 사이트는 회원가입이나 자체 온라인 주문 폼을 운영하지 않으며 고객 개인정보를 직접 저장하는 기능이 없습니다.</p><p>전화, 지도 또는 외부 주문 플랫폼으로 이동한 뒤의 개인정보 처리는 각 서비스의 정책을 따릅니다.</p><p>향후 개인정보를 직접 수집하는 기능이 추가되면 수집 항목·목적·보유기간을 이 문서에 반영합니다.</p><p>시행일: 2026-08-10</p>`);
fs.writeFileSync(path.join(out,'index.html'), html);
fs.writeFileSync(path.join(out,'terms.html'), terms);
fs.writeFileSync(path.join(out,'privacy.html'), privacy);
fs.writeFileSync(path.join(out,'robots.txt'), 'User-agent: *\nAllow: /\nSitemap: https://jadam-maru.pages.dev/sitemap.xml\n');
fs.writeFileSync(path.join(out,'sitemap.xml'), '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://jadam-maru.pages.dev/</loc></url></urlset>');
console.log('✅ dist 생성 완료');
